services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .data/rabbit/:/var/lib/rabbitmq/

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - .data/mongo/:/data/db

  cryptor-trends-gemini-bot:
    image: cryptor-trends-gemini-bot
    container_name: 'cryptor-trends-gemini-bot'
    build:
      context: ./src/cryptor-trends-gemini-bot
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - src/cryptor-trends-gemini-bot/.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=cryptor-trends-gemini-bot
      - RABBITMQ_DLQ_QUEUE_NAME=dlq-cryptor-trends-gemini-bot
      - RABBITMQ_CONSUME_QUEUE_NAME=cryptor-trends-coin-bot
      - RABBITMQ_CONSUME_DLQ_QUEUE_NAME=dlq-cryptor-trends-coin-bot
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=cryptor-gemini
      - GEMINI_MODEL_NAME=gemini-1.0-pro

  cryptor-trends-api:
    image: cryptor-trends-api
    container_name: 'cryptor-trends-api'
    build:
      context: ./src/cryptor-trends-api
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - src/cryptor-trends-api/.env
    ports:
      - 8000:8000
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_CONSUME_QUEUE_NAME=cryptor-trends-gemini-bot
      - RABBITMQ_CONSUME_DLQ_QUEUE_NAME=dlq-cryptor-trends-gemini-bot
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=cryptor-api
      - MONGO_COLLECTION=cryptor-trends

  cryptor-trends-coin-bot:
    image: cryptor-trends-coin-bot
    container_name: 'cryptor-trends-coin-bot'
    build:
      context: ./src/cryptor-trends-coin-bot
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - src/cryptor-trends-coin-bot/.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=cryptor-trends-coin-bot
      - RABBITMQ_DLQ_QUEUE_NAME=dlq-cryptor-trends-coin-bot
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=cryptor-trends

  cryptor-trends-front:
    image: cryptor-trends-front
    container_name: 'cryptor-trends-front'
    build:
      context: ./src/cryptor-trends-front
      dockerfile: Dockerfile
    depends_on:
      cryptor-trends-api:
        condition: service_started
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL= http://crypto-trends.juliosaraiva.com:8000/v1/cryptocurrency
      - NEXT_PUBLIC_TELEGRAM_URL= https://t.me/Crypto_Trends_Robot_bot
