version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - .data/rabbit/:/var/lib/rabbitmq/

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - .data/mongo/:/data/db

  cryptor-trends-dataset:
    image: cryptor-trends-dataset
    container_name: 'cryptor-trends-dataset'
    build:
      context: ./src/cryptor-trends-dataset
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./src/cryptor-trends-dataset:/app
    env_file:
      - src/cryptor-trends-dataset/.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=cryptor-trends-dataset

  cryptor-trends-coin-bot:
    image: cryptor-trends-coin-bot
    container_name: 'cryptor-trends-coin-bot'
    build:
      context: ./src/cryptor-trends-coin-bot
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - src/cryptor-trends-coin-bot/.env
    volumes:
      - ./src/cryptor-trends-coin-bot:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=cryptor-trends-coin-bot
      - RABBITMQ_DLQ_QUEUE_NAME=dlq-cryptor-trends-coin-bot
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=cryptor-trends

  cryptor-trends-gemini-bot:
    image: cryptor-trends-gemini-bot
    container_name: 'cryptor-trends-gemini-bot'
    build:
      context: ./src/cryptor-trends-gemini-bot
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - src/cryptor-trends-gemini-bot/.env
    volumes:
      - ./src/cryptor-trends-gemini-bot:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE_NAME=cryptor-trends-gemini-bot
      - RABBITMQ_DLQ_QUEUE_NAME=dlq-cryptor-trends-gemini-bot
      - RABBITMQ_CONSUME_QUEUE_NAME=cryptor-trends-coin-bot
      - RABBITMQ_CONSUME_DLQ_QUEUE_NAME=dlq-cryptor-trends-coin-bot
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=cryptor-gemini
